### ISSUE TITLE
Query limit attribute not being updated after query already created

### ISSUE THREAD

**Issue by juan-vg** [honeycombio/terraform-provider-honeycombio#497] opened 2024-07-15 11:34 UTC
**Versions**

v0.23.0

**Steps to reproduce**

1. Create a `honeycombio_query` based on a `honeycombio_query_specification` datasource, specifying a `limit` value between 1 and 1000.
2. Try to create a `honeycombio_trigger` based on that `honeycombio_query`. It fails because `honeycombio_trigger` doesn't allow a `honeycombio_query` with `limit` defined.
3. Remove the `limit` from the `honeycombio_query_specification` datasource.
4. The already created `honeycombio_query` still has the limit, so the `honeycombio_trigger` can't be created.

**Additional context**

To solve the issue, the `honeycombio_query` must be destroyed and recreated again. Instead, the `honeycombio_query_specification` change should trigger another change in the `honeycombio_query` to remove the limit attribute from `honeycombio_query.query_json`.

**I have not checked if this happens for other attributes, but I believe it does.**

**I have not checked if this happens for v0.24.0, but I believe it does.**

**Comment by juan-vg** [comment] 2024-07-15 11:48
Since the queries seem to be immutable (and I believe that's why any change is discarded), I think that any change to the `honeycombio_query_specification` should trigger a `honeycombio_query` recreation.

**Comment by jharley** [comment] 2024-07-15 13:46
@juan-vg thanks for reporting this! You are correct that queries are immutable.

It does indeed sound like a bug in either the query specification data source or the query resource. We'll take a look at it shortly.

**Comment by jharley** [comment] 2024-07-17 18:46
@juan-vg I just had a chance to investigate this and cannot reproduce the bug using what you describe above on 0.24.0. Can you try upgrading to see if that resolves the issue for you?

**Comment by jharley** [comment] 2024-07-29 14:05
Hey, @juan-vg. Did you have any luck here?

**Comment by juan-vg** [comment] 2024-07-31 10:52
Hey @jharley, excuse the delay. Nope, I've had no time yet to focus on this topic. Hopefully it's already solved in 0.24

**Comment by jharley** [comment] 2024-07-31 11:53
@juan-vg No problem! I'm going to close this out but feel free to re-open or open a new issue if you encounter the issue -- or any others!

**Closed by jharley** 2024-07-31 11:53 UTC
Labels: bug
